services:
  # Servico do Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: irrigador_db
    ports:
      - "5432:5432"
    volumes:
      - irrigador-pg-data:/var/lib/postgresql/data
    networks:
      - irrigador-net

  # Servi√ßo da Interface grafica PgAdmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - irrigador-net
    depends_on:
      - postgres-db

  #Servico do RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # Porta para o Spring se conectar
      - "15672:15672" # Porta para a interface web
      - "1883:1883"   # Porta para o protocolo MQTT
    networks:
      - irrigador-net
networks:
  irrigador-net:
    driver: bridge

volumes:
  irrigador-pg-data: {}